name: TATAPLAY Origin Generator

on:
  schedule:
    - cron: "0 */2 * * *"
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python

        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run updater script
        run: |
          pip3 install -r requirements.txt
          python3 updater.py

      - name: Commit data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add origin.json
          git commit -m "Updated via AutoBot 🤖" || echo "No changes to commit"
          git push
